import { Athlete, Session, Feedback, Invoice, CrmCard, Message, Revenue } from './types'

export const athletes: Athlete[] = [
  {
    id: 'a1',
    name: 'Katarzyna Wiśniewska',
    avatar: 'KW',
    goal: 'Maraton sub-3:30',
    package: 'Pro',
    packagePrice: 599,
    status: 'ok',
    lastTraining: '2026-02-27',
    lastContact: 1,
    joinDate: '2024-09-01',
    email: 'katarzyna@email.com',
    phone: '+48 601 234 567',
    age: 32,
    city: 'Warszawa',
    personalBests: { '5km': '22:14', '10km': '46:30', 'HM': '1:43:12', 'Marathon': '3:42:00' },
    injuries: [],
    coachNotes: 'Świetna zawodniczka, bardzo zmotywowana. Tendencja do przyspieszania na początku biegu. Pracujemy nad równomiernym tempem.',
    totalPaid: 4792,
  },
  {
    id: 'a2',
    name: 'Marek Kowalczyk',
    avatar: 'MK',
    goal: '10km sub-40min',
    package: 'Standard',
    packagePrice: 399,
    status: 'warning',
    lastTraining: '2026-02-24',
    lastContact: 4,
    joinDate: '2025-01-15',
    email: 'marek.k@email.com',
    phone: '+48 602 345 678',
    age: 28,
    city: 'Kraków',
    personalBests: { '5km': '20:45', '10km': '42:10' },
    injuries: ['Shin splints (2024)'],
    coachNotes: 'Biegacz z potencjałem, ale problem z konsekwencją treningu. Często pomija sesje regeneracyjne.',
    totalPaid: 1596,
    alertMessage: '4 dni bez kontaktu',
  },
  {
    id: 'a3',
    name: 'Anna Dąbrowska',
    avatar: 'AD',
    goal: 'Pierwsza "5" poniżej 25min',
    package: 'Starter',
    packagePrice: 249,
    status: 'ok',
    lastTraining: '2026-02-28',
    lastContact: 0,
    joinDate: '2025-11-01',
    email: 'anna.d@email.com',
    phone: '+48 603 456 789',
    age: 35,
    city: 'Wrocław',
    personalBests: { '5km': '27:30' },
    injuries: [],
    coachNotes: 'Początkująca biegaczka, duży postęp w ostatnich 3 miesiącach. Bardzo sumiennie podchodzi do planu.',
    totalPaid: 747,
  },
  {
    id: 'a4',
    name: 'Piotr Zielński',
    avatar: 'PZ',
    goal: 'Ironman 70.3',
    package: 'Pro',
    packagePrice: 599,
    status: 'alert',
    lastTraining: '2026-02-20',
    lastContact: 8,
    joinDate: '2024-06-01',
    email: 'piotr.z@email.com',
    phone: '+48 604 567 890',
    age: 41,
    city: 'Gdańsk',
    personalBests: { '5km': '21:00', '10km': '43:30', 'HM': '1:48:00', 'Sprint Tri': '1:12:00' },
    injuries: ['Kolano biegacza (2025)', 'Naderwanie ścięgna Achillesa (2024)'],
    coachNotes: 'Doświadczony triathlonista. Tendencja do przetrenowania. Ostatnio nieobecny — sprawdzić co się dzieje.',
    totalPaid: 5990,
    alertMessage: '8 dni bez kontaktu, możliwe odejście',
  },
  {
    id: 'a5',
    name: 'Monika Lewandowska',
    avatar: 'ML',
    goal: 'Half-marathon sub-1:50',
    package: 'Standard',
    packagePrice: 399,
    status: 'ok',
    lastTraining: '2026-02-27',
    lastContact: 1,
    joinDate: '2025-04-01',
    email: 'monika.l@email.com',
    phone: '+48 605 678 901',
    age: 29,
    city: 'Poznań',
    personalBests: { '5km': '23:45', '10km': '49:20', 'HM': '1:54:00' },
    injuries: [],
    coachNotes: 'Bardzo regularna zawodniczka. Świetnie reaguje na feedback. PB poprawiane co miesiąc.',
    totalPaid: 3990,
  },
  {
    id: 'a6',
    name: 'Tomasz Nowak',
    avatar: 'TN',
    goal: 'Maraton sub-4:00',
    package: 'Pro',
    packagePrice: 599,
    status: 'warning',
    lastTraining: '2026-02-25',
    lastContact: 3,
    joinDate: '2024-12-01',
    email: 'tomasz.n@email.com',
    phone: '+48 606 789 012',
    age: 45,
    city: 'Łódź',
    personalBests: { '5km': '24:30', '10km': '51:00', 'HM': '1:58:00' },
    injuries: ['Ból kolan (przewlekły)'],
    coachNotes: 'Maratończyk-amator. Ograniczenia ortopedyczne. Plan zmodyfikowany o ćwiczenia wzmacniające.',
    totalPaid: 1796,
    alertMessage: 'Pominął 2 sesje z rzędu',
  },
]

// Helper to create ISO date relative to today
const d = (daysOffset: number): string => {
  const date = new Date('2026-02-28')
  date.setDate(date.getDate() + daysOffset)
  return date.toISOString().split('T')[0]
}

export const sessions: Session[] = [
  // Katarzyna (a1)
  { id: 's1', athleteId: 'a1', date: d(-14), type: 'easy', title: 'Rozbieganie', description: 'Spokojny bieg tlenowy', plannedDistance: 10, plannedDuration: 65, plannedPace: '6:30', actualDistance: 10.2, actualDuration: 64, actualPace: '6:17', avgHR: 138, maxHR: 152, completed: true, feedbackId: 'f1' },
  { id: 's2', athleteId: 'a1', date: d(-12), type: 'interval', title: 'Interwały 5x1km', description: '5x1km w tempie 4:45/km, przerwa 90s', plannedDistance: 12, plannedDuration: 70, plannedPace: '4:45', actualDistance: 12.1, actualDuration: 72, actualPace: '4:48', avgHR: 162, maxHR: 178, completed: true, feedbackId: 'f2' },
  { id: 's3', athleteId: 'a1', date: d(-10), type: 'easy', title: 'Regeneracja', description: 'Bardzo spokojny bieg', plannedDistance: 8, plannedDuration: 55, plannedPace: '6:50', actualDistance: 8.0, actualDuration: 56, actualPace: '7:00', avgHR: 128, maxHR: 140, completed: true },
  { id: 's4', athleteId: 'a1', date: d(-9), type: 'gym', title: 'Siłownia', description: 'Wzmacnianie core i nóg', plannedDuration: 60, completed: true },
  { id: 's5', athleteId: 'a1', date: d(-7), type: 'tempo', title: 'Bieg progowy', description: '5km w tempie progowym 5:00/km', plannedDistance: 12, plannedDuration: 60, plannedPace: '5:00', actualDistance: 11.8, actualDuration: 61, actualPace: '5:10', avgHR: 155, maxHR: 168, completed: true, feedbackId: 'f3' },
  { id: 's6', athleteId: 'a1', date: d(-5), type: 'easy', title: 'Rozbieganie', description: 'Spokojny bieg regeneracyjny', plannedDistance: 8, plannedDuration: 52, plannedPace: '6:30', actualDistance: 8.3, actualDuration: 54, actualPace: '6:30', avgHR: 133, maxHR: 145, completed: true },
  { id: 's7', athleteId: 'a1', date: d(-3), type: 'long', title: 'Długi bieg', description: 'Long run w tempie maratońskim', plannedDistance: 24, plannedDuration: 140, plannedPace: '5:50', actualDistance: 24.2, actualDuration: 142, actualPace: '5:52', avgHR: 148, maxHR: 162, completed: true, feedbackId: 'f4' },
  { id: 's8', athleteId: 'a1', date: d(-1), type: 'easy', title: 'Trucht regeneracyjny', description: 'Bardzo wolno', plannedDistance: 6, plannedDuration: 45, plannedPace: '7:30', actualDistance: 6.1, actualDuration: 44, actualPace: '7:13', avgHR: 122, maxHR: 132, completed: true, feedbackId: 'f5' },
  { id: 's9', athleteId: 'a1', date: d(0), type: 'interval', title: 'Interwały 8x400m', description: '8x400m w tempie 4:30/km', plannedDistance: 10, plannedDuration: 55, plannedPace: '4:30', completed: false },
  { id: 's10', athleteId: 'a1', date: d(2), type: 'easy', title: 'Rozbieganie', description: 'Spokojny bieg', plannedDistance: 10, plannedDuration: 65, completed: false },
  { id: 's11', athleteId: 'a1', date: d(4), type: 'tempo', title: 'Bieg progowy', description: 'Progi 3x10min', plannedDistance: 14, plannedDuration: 75, completed: false },
  { id: 's12', athleteId: 'a1', date: d(7), type: 'long', title: 'Długi bieg 26km', description: 'Kluczowy long run tygodnia', plannedDistance: 26, plannedDuration: 152, completed: false },

  // Marek (a2)
  { id: 's13', athleteId: 'a2', date: d(-14), type: 'easy', title: 'Rozbieganie', description: 'Start tygodnia', plannedDistance: 8, plannedDuration: 50, actualDistance: 8.5, actualDuration: 49, completed: true },
  { id: 's14', athleteId: 'a2', date: d(-12), type: 'interval', title: 'Interwały górskie', description: 'Podbiegi 6x200m', plannedDistance: 10, plannedDuration: 60, completed: false },
  { id: 's15', athleteId: 'a2', date: d(-9), type: 'tempo', title: 'Tempo run', description: '20min w tempie progowym', plannedDistance: 12, plannedDuration: 65, actualDistance: 12.0, actualDuration: 66, completed: true, feedbackId: 'f6' },
  { id: 's16', athleteId: 'a2', date: d(-5), type: 'easy', title: 'Bieg regeneracyjny', description: 'Po intensywnym tygodniu', plannedDistance: 6, plannedDuration: 40, actualDistance: 6.2, actualDuration: 41, completed: true },
  { id: 's17', athleteId: 'a2', date: d(-3), type: 'long', title: 'Długi bieg 16km', description: 'Budowanie bazy', plannedDistance: 16, plannedDuration: 95, completed: false },
  { id: 's18', athleteId: 'a2', date: d(1), type: 'interval', title: 'Interwały 4x1km', description: 'Kluczowa sesja prędkości', plannedDistance: 10, plannedDuration: 60, completed: false },
  { id: 's19', athleteId: 'a2', date: d(3), type: 'easy', title: 'Rozbieganie', description: 'Regeneracja', plannedDistance: 8, plannedDuration: 52, completed: false },

  // Anna (a3)
  { id: 's20', athleteId: 'a3', date: d(-14), type: 'easy', title: 'Bieg 4km', description: 'Bieg ciągły', plannedDistance: 4, plannedDuration: 30, actualDistance: 4.0, actualDuration: 29, completed: true },
  { id: 's21', athleteId: 'a3', date: d(-11), type: 'easy', title: 'Interwały chód/bieg', description: '5x(4min bieg + 1min marsz)', plannedDistance: 5, plannedDuration: 35, actualDistance: 5.1, actualDuration: 35, completed: true, feedbackId: 'f7' },
  { id: 's22', athleteId: 'a3', date: d(-8), type: 'easy', title: 'Bieg 5km', description: 'Pierwszy ciągły 5km!', plannedDistance: 5, plannedDuration: 35, actualDistance: 5.0, actualDuration: 33, completed: true, feedbackId: 'f8' },
  { id: 's23', athleteId: 'a3', date: d(-5), type: 'gym', title: 'Ćwiczenia wzmacniające', description: 'Core, nogi, mobilność', plannedDuration: 45, completed: true },
  { id: 's24', athleteId: 'a3', date: d(-2), type: 'easy', title: 'Bieg 6km', description: 'Zwiększamy dystans', plannedDistance: 6, plannedDuration: 42, actualDistance: 6.0, actualDuration: 41, completed: true, feedbackId: 'f9' },
  { id: 's25', athleteId: 'a3', date: d(0), type: 'easy', title: 'Bieg tempo 4km', description: 'Szybszy bieg krótszy dystans', plannedDistance: 4, plannedDuration: 26, completed: false },
  { id: 's26', athleteId: 'a3', date: d(3), type: 'easy', title: 'Bieg 7km', description: 'Kolejny rekord dystansu', plannedDistance: 7, plannedDuration: 49, completed: false },

  // Piotr (a4)
  { id: 's27', athleteId: 'a4', date: d(-21), type: 'easy', title: 'Bieg spokojny', description: 'Po kontuzji', plannedDistance: 8, plannedDuration: 55, actualDistance: 7.5, actualDuration: 57, completed: true },
  { id: 's28', athleteId: 'a4', date: d(-18), type: 'gym', title: 'Rehabilitacja + Siłownia', description: 'Ćwiczenia rehabilitacyjne kolana', plannedDuration: 60, completed: true },
  { id: 's29', athleteId: 'a4', date: d(-14), type: 'easy', title: 'Bieg testowy', description: 'Sprawdzamy kolano', plannedDistance: 10, plannedDuration: 65, completed: false },
  { id: 's30', athleteId: 'a4', date: d(-10), type: 'rest', title: 'Odpoczynek', description: 'Zalecony odpoczynek', plannedDuration: 0, completed: true },
  { id: 's31', athleteId: 'a4', date: d(-7), type: 'easy', title: 'Powrót do treningu', description: 'Delikatnie', plannedDistance: 12, plannedDuration: 75, completed: false },

  // Monika (a5)
  { id: 's32', athleteId: 'a5', date: d(-13), type: 'easy', title: 'Rozbieganie', description: 'Spokojny start', plannedDistance: 10, plannedDuration: 62, actualDistance: 10.3, actualDuration: 62, completed: true },
  { id: 's33', athleteId: 'a5', date: d(-11), type: 'interval', title: 'Interwały 6x800m', description: 'Prędkość na 800m', plannedDistance: 14, plannedDuration: 75, actualDistance: 14.0, actualDuration: 74, completed: true, feedbackId: 'f10' },
  { id: 's34', athleteId: 'a5', date: d(-8), type: 'tempo', title: 'Bieg progowy', description: '25min w tempie half', plannedDistance: 14, plannedDuration: 72, actualDistance: 14.1, actualDuration: 72, completed: true },
  { id: 's35', athleteId: 'a5', date: d(-5), type: 'long', title: 'Długi bieg 18km', description: 'Budowanie wytrzymałości', plannedDistance: 18, plannedDuration: 105, actualDistance: 18.2, actualDuration: 106, completed: true, feedbackId: 'f11' },
  { id: 's36', athleteId: 'a5', date: d(-2), type: 'easy', title: 'Regeneracja', description: 'Lekko', plannedDistance: 8, plannedDuration: 52, actualDistance: 8.1, actualDuration: 52, completed: true },
  { id: 's37', athleteId: 'a5', date: d(1), type: 'interval', title: 'Interwały 10x400m', description: 'Szybkość końcowa', plannedDistance: 12, plannedDuration: 65, completed: false },
  { id: 's38', athleteId: 'a5', date: d(4), type: 'long', title: 'Długi bieg 20km', description: 'Kluczowy long run', plannedDistance: 20, plannedDuration: 116, completed: false },

  // Tomasz (a6)
  { id: 's39', athleteId: 'a6', date: d(-14), type: 'easy', title: 'Rozbieganie', description: 'Spokojnie, kontrola kolan', plannedDistance: 8, plannedDuration: 56, actualDistance: 8.0, actualDuration: 57, completed: true },
  { id: 's40', athleteId: 'a6', date: d(-11), type: 'gym', title: 'Siłownia wzmacniająca', description: 'Nogi, biodra, core', plannedDuration: 60, completed: true },
  { id: 's41', athleteId: 'a6', date: d(-9), type: 'easy', title: 'Bieg 10km', description: 'Medium effort', plannedDistance: 10, plannedDuration: 68, completed: false },
  { id: 's42', athleteId: 'a6', date: d(-6), type: 'tempo', title: 'Tempo run 8km', description: 'Przy granicy progowej', plannedDistance: 12, plannedDuration: 70, completed: false },
  { id: 's43', athleteId: 'a6', date: d(-3), type: 'long', title: 'Długi bieg 18km', description: 'Weekend long', plannedDistance: 18, plannedDuration: 108, completed: false },
  { id: 's44', athleteId: 'a6', date: d(2), type: 'easy', title: 'Rozbieganie 8km', description: 'Regeneracja', plannedDistance: 8, plannedDuration: 55, completed: false },
]

export const feedbacks: Feedback[] = [
  {
    id: 'f1', athleteId: 'a1', sessionId: 's1', date: d(-14), source: 'voice', signal: 'green',
    transcript: 'Dzisiaj bieg poszedł naprawdę dobrze. Czułam się lekko przez całą drogę, tętno było spokojne, nie forsowałam się. Nogi nie bolą, humor super. Chyba właściwie regeneruję się po ubiegłym tygodniu.',
    aiAnalysis: 'Zawodniczka wykazuje dobre oznaki adaptacji treningowej. Subiektywne odczucia (lekkość, energia) korelują z danymi z zegarka — SR 138bpm to strefa 2. Brak oznak zmęczenia.',
    aiSummary: 'Dobra regeneracja, gotowość do kolejnej sesji',
    watchData: { avgHR: 138, maxHR: 152, distance: 10.2, pace: '6:17', cadence: 172, calories: 520 },
    read: true,
  },
  {
    id: 'f2', athleteId: 'a1', sessionId: 's2', date: d(-12), source: 'voice', signal: 'green',
    transcript: 'Interwały poszły świetnie! Pierwsze 3 powtórzenia były nieco szybsze niż plan, ale kontrolowałam się i ostatnie 2 były dokładnie w tempie. Nogi trochę palone po treningu, ale to normalne. Jutro mam wolne więc mogę odpocząć.',
    aiAnalysis: 'Sesja wykonana z lekkim przekroczeniem intensywności (SR 162 vs planowane ~158). Zawodniczka sama to zauważyła i dokonała korekty. Pozytywny sygnał samokontoli. Zalecam przypomnienie o równomiernym rozkładzie.',
    aiSummary: 'Interwały wykonane, lekkie przekroczenie tempa na początku',
    watchData: { avgHR: 162, maxHR: 178, distance: 12.1, pace: '4:48', cadence: 182, calories: 680 },
    read: true,
  },
  {
    id: 'f3', athleteId: 'a1', sessionId: 's5', date: d(-7), source: 'text', signal: 'yellow',
    transcript: 'Bieg progowy był ciężki. Nie udało mi się utrzymać tempa 5:00 — wyszło 5:10. Nogi były ciężkie od początku, może za mało spałam ostatnio. Myślę że potrzebuję więcej czasu na regenerację.',
    aiAnalysis: 'Gorsze tempo może wynikać z niedoboru snu (zawodniczka wspomina). HRV z zegarka na poziomie 58ms (vs. bazowe 72ms) potwierdza niedostateczną regenerację. Rozważyć zmniejszenie objętości w tym tygodniu.',
    aiSummary: 'Przekroczenie tempa progowego, oznaki zmęczenia, monitoruj regenerację',
    watchData: { avgHR: 155, maxHR: 168, distance: 11.8, pace: '5:10', hrv: 58, calories: 610 },
    coachReply: 'Katarzyno, bez stresu! Bieg przy zmęczeniu to i tak wartościowa sesja. Zadbaj o 8h snu i jutro biegaj bardzo spokojnie. W tym tygodniu skracamy piątkowe interwały o 2 powtórzenia.',
    read: true,
  },
  {
    id: 'f4', athleteId: 'a1', sessionId: 's7', date: d(-3), source: 'voice', signal: 'green',
    transcript: 'Długi bieg był genialny! 24km i czułam się świeżo na końcu. Tempo maratońskie trzymało mi się samo, HR był stabilny. Zaczyna mi się to podobać. Po biegu rozciąganie, dużo wody.',
    aiAnalysis: 'Doskonały wynik. Tempo 5:52 przy SR 148bpm to efektywność tlenowa — zawodniczka wchodzi w dobrą formę. Tempo stabilne przez cały dystans (brak "wybuchu" na początku). Pozytywna reakcja treningowa.',
    aiSummary: 'Doskonały długi bieg, stabilne tempo, wysoka efektywność tlenowa',
    watchData: { avgHR: 148, maxHR: 162, distance: 24.2, pace: '5:52', hrv: 74, cadence: 176, calories: 1250 },
    read: false,
  },
  {
    id: 'f5', athleteId: 'a1', sessionId: 's8', date: d(-1), source: 'auto', signal: 'green',
    transcript: 'Dane automatycznie zebrane z Apple Watch. Zawodniczka nie zostawiła komentarza.',
    aiAnalysis: 'Sesja regeneracyjna wykonana zgodnie z planem. Tętno w dolnej strefie 1. Brak anomalii.',
    aiSummary: 'Regeneracja wykonana prawidłowo',
    watchData: { avgHR: 122, maxHR: 132, distance: 6.1, pace: '7:13', cadence: 165, calories: 310 },
    read: false,
  },
  {
    id: 'f6', athleteId: 'a2', sessionId: 's15', date: d(-9), source: 'text', signal: 'yellow',
    transcript: 'Tempo run się udał ale nogi były ciężkie. Chyba za szybko wróciłem po przerwie. Może potrzebuję jeszcze tygodnia spokojniejszego treningu?',
    aiAnalysis: 'Marek wrócił po 5-dniowej przerwie (brak aktywności w danych) z sesją o średniej intensywności. Subiektywne odczucie ciężkości nóg jest typowe po przerwie. Warto stopniować powrót.',
    aiSummary: 'Powrót po przerwie, subiektywne zmęczenie nóg',
    watchData: { avgHR: 158, maxHR: 172, distance: 12.0 },
    read: true,
  },
  {
    id: 'f7', athleteId: 'a3', sessionId: 's21', date: d(-11), source: 'voice', signal: 'green',
    transcript: 'Oho, pierwsze interwały chód-bieg i chyba mi wychodzi! Cztery minuty biegu z rzędu, wcześniej myślałam że to niemożliwe. Jestem z siebie dumna!',
    aiAnalysis: 'Bardzo pozytywna sesja. Anna wykazuje wysoki poziom motywacji, co jest kluczowe na etapie budowania nawyku biegania. Postęp zgodny z planem.',
    aiSummary: 'Świetna motywacja, wykonanie planu ponad oczekiwania',
    read: true,
  },
  {
    id: 'f8', athleteId: 'a3', sessionId: 's22', date: d(-8), source: 'voice', signal: 'green',
    transcript: 'Zrobiłam 5km bez przerwy!!! Nie mogę uwierzyć! Miesiąc temu ledwie 1km. Tempo nie było szybkie ale nie ważne, dobiegłam! Trochę boli lewa łydka ale to pewnie zakwasy.',
    aiAnalysis: 'Przełomowy moment dla zawodniczki. Wzmianka o bólu lewej łydki wymaga monitorowania — przy zakwasach (DOMS) nie ma powodów do niepokoju, ale warto zapytać przy kolejnym kontakcie.',
    aiSummary: 'Przełomowe 5km! Monitorować lewą łydkę',
    read: true,
    coachReply: 'Brawo Ania!!! Pierwsze 5km to wielki krok! Co do łydki — to normalne przy nowym bodźcu treningowym. Rozciągaj się, może roluj. Jeśli boli przy biegu (nie po) — daj znać.',
  },
  {
    id: 'f9', athleteId: 'a3', sessionId: 's24', date: d(-2), source: 'voice', signal: 'green',
    transcript: '6km i czuję się coraz pewniej. Łydka już nie boli. Tempo spokojne, HR w normie. Zaczynam rozumieć dlaczego ludzie biegają.',
    aiAnalysis: 'Dobra progresja. Brak bólu łydki — zakwasy minęły zgodnie z oczekiwaniami. Zawodniczka buduje pewność siebie w biegu, co jest kluczowe na tym etapie.',
    aiSummary: 'Dobra progresja, brak bólu, rosnąca pewność siebie',
    read: false,
  },
  {
    id: 'f10', athleteId: 'a5', sessionId: 's33', date: d(-11), source: 'voice', signal: 'green',
    transcript: 'Interwały 800m poszły bardzo dobrze. Trzymałam tempo, każde powtórzenie lepsze niż poprzednie. Czuję wyraźną poprawę od początku roku.',
    aiAnalysis: 'Negatywny split na interwałach (każde powtórzenie szybsze) to doskonały wskaźnik dystrybucji wysiłku. Monika jest w dobrej formie.',
    aiSummary: 'Doskonałe interwały z negatywnym splitem',
    watchData: { avgHR: 161, maxHR: 175, distance: 14.0 },
    read: true,
  },
  {
    id: 'f11', athleteId: 'a5', sessionId: 's35', date: d(-5), source: 'text', signal: 'green',
    transcript: 'Długi bieg 18km za mną. Pierwsze 12km zgodnie z planem, ostatnie 6 przyspieszyłam bo czułam się dobrze. HR był trochę wyższy na końcu ale w normie. Nogi zmęczone ale zadowolona.',
    aiAnalysis: 'Przyspieszenie na końcu długiego biegu to pozytywny sygnał gotowości formy. Uważać na nawyk przyspieszania — przy intensywniejszym planie może prowadzić do przetrenowania.',
    aiSummary: 'Dobry long run, tendencja do przyspieszania na końcu — warto omówić',
    watchData: { avgHR: 152, maxHR: 168, distance: 18.2, cadence: 174, calories: 940 },
    read: false,
  },
]

export const invoices: Invoice[] = [
  { id: 'i1', athleteId: 'a1', number: 'FV/2026/001', date: '2026-02-01', dueDate: '2026-02-14', amount: 599, status: 'paid', package: 'Pro', description: 'Plan Pro — Luty 2026' },
  { id: 'i2', athleteId: 'a1', number: 'FV/2026/002', date: '2026-03-01', dueDate: '2026-03-14', amount: 599, status: 'pending', package: 'Pro', description: 'Plan Pro — Marzec 2026' },
  { id: 'i3', athleteId: 'a2', number: 'FV/2026/003', date: '2026-02-01', dueDate: '2026-02-14', amount: 399, status: 'paid', package: 'Standard', description: 'Plan Standard — Luty 2026' },
  { id: 'i4', athleteId: 'a2', number: 'FV/2026/004', date: '2026-03-01', dueDate: '2026-03-14', amount: 399, status: 'pending', package: 'Standard', description: 'Plan Standard — Marzec 2026' },
  { id: 'i5', athleteId: 'a3', number: 'FV/2026/005', date: '2026-02-01', dueDate: '2026-02-14', amount: 249, status: 'paid', package: 'Starter', description: 'Plan Starter — Luty 2026' },
  { id: 'i6', athleteId: 'a4', number: 'FV/2026/006', date: '2026-02-01', dueDate: '2026-02-14', amount: 599, status: 'overdue', package: 'Pro', description: 'Plan Pro — Luty 2026' },
  { id: 'i7', athleteId: 'a4', number: 'FV/2026/007', date: '2026-01-01', dueDate: '2026-01-14', amount: 599, status: 'overdue', package: 'Pro', description: 'Plan Pro — Styczeń 2026' },
  { id: 'i8', athleteId: 'a5', number: 'FV/2026/008', date: '2026-02-01', dueDate: '2026-02-14', amount: 399, status: 'paid', package: 'Standard', description: 'Plan Standard — Luty 2026' },
  { id: 'i9', athleteId: 'a5', number: 'FV/2026/009', date: '2026-03-01', dueDate: '2026-03-14', amount: 399, status: 'pending', package: 'Standard', description: 'Plan Standard — Marzec 2026' },
  { id: 'i10', athleteId: 'a6', number: 'FV/2026/010', date: '2026-02-01', dueDate: '2026-02-14', amount: 599, status: 'paid', package: 'Pro', description: 'Plan Pro — Luty 2026' },
  { id: 'i11', athleteId: 'a6', number: 'FV/2026/011', date: '2026-03-01', dueDate: '2026-03-14', amount: 599, status: 'pending', package: 'Pro', description: 'Plan Pro — Marzec 2026' },
  { id: 'i12', athleteId: 'a1', number: 'FV/2026/012', date: '2026-01-01', dueDate: '2026-01-14', amount: 599, status: 'paid', package: 'Pro', description: 'Plan Pro — Styczeń 2026' },
  { id: 'i13', athleteId: 'a3', number: 'FV/2026/013', date: '2026-01-01', dueDate: '2026-01-14', amount: 249, status: 'paid', package: 'Starter', description: 'Plan Starter — Styczeń 2026' },
  { id: 'i14', athleteId: 'a5', number: 'FV/2026/014', date: '2026-01-01', dueDate: '2026-01-14', amount: 399, status: 'paid', package: 'Standard', description: 'Plan Standard — Styczeń 2026' },
  { id: 'i15', athleteId: 'a2', number: 'FV/2025/015', date: '2025-12-01', dueDate: '2025-12-14', amount: 399, status: 'cancelled', package: 'Standard', description: 'Plan Standard — Grudzień 2025' },
]

export const crmCards: CrmCard[] = [
  { id: 'c1', name: 'Bartłomiej Wróbel', email: 'bartlomiej@email.com', source: 'Instagram', status: 'inquiry', notes: 'Zapytał o pakiet Pro dla maratonu', createdAt: d(-3), interest: 'Maraton sub-3:45', value: 599 },
  { id: 'c2', name: 'Joanna Kamińska', email: 'joanna.k@email.com', phone: '+48 607 111 222', source: 'Polecenie', status: 'conversation', notes: 'Rozmowa telefoniczna odbyła się, zainteresowana ofertą', createdAt: d(-8), interest: 'Half-marathon', value: 399 },
  { id: 'c3', name: 'Rafał Szymański', email: 'rafal.s@email.com', source: 'Strona WWW', status: 'offer', notes: 'Wysłana oferta. Czeka na decyzję.', createdAt: d(-12), interest: '10km racing', value: 399 },
  { id: 'c4', name: 'Agata Wójcik', email: 'agata.w@email.com', source: 'Instagram', status: 'onboarding', notes: 'Opłata wstępna przyjęta, tworzymy plan startowy', createdAt: d(-5), interest: 'Pierwsze 5km', value: 249 },
  { id: 'c5', name: 'Katarzyna Wiśniewska', email: 'katarzyna@email.com', source: 'Strona WWW', status: 'active', notes: 'Aktywna zawodniczka', createdAt: '2024-09-01', interest: 'Maraton sub-3:30', value: 599 },
  { id: 'c6', name: 'Marek Kowalczyk', email: 'marek.k@email.com', source: 'Polecenie', status: 'active', notes: 'Aktywny zawodnik, lekkie problemy z regularność', createdAt: '2025-01-15', interest: '10km sub-40', value: 399 },
  { id: 'c7', name: 'Sebastian Krawczyk', email: 'sebastian@email.com', source: 'Strava', status: 'ended', notes: 'Zakończył współpracę po 3 miesiącach — zmiana miasta', createdAt: d(-90), interest: 'Triathlon', value: 599 },
  { id: 'c8', name: 'Magdalena Czarnecka', email: 'magda.c@email.com', source: 'Instagram', status: 'inquiry', notes: 'Pierwsza wiadomość, bez odpowiedzi jeszcze', createdAt: d(-1), interest: 'Bieganie dla zdrowia', value: 249 },
]

export const messages: Message[] = [
  { id: 'm1', senderId: 'coach', content: 'Cześć Katarzyno! Jak samopoczucie po wczorajszym długim biegu?', timestamp: d(-3) + 'T09:00:00', read: true },
  { id: 'm2', senderId: 'a1', content: 'Super! Nogi trochę zmęczone ale humor doskonały. Ten bieg to było coś!', timestamp: d(-3) + 'T09:15:00', read: true },
  { id: 'm3', senderId: 'coach', content: 'Widać to po danych :) Efektywność tlenowa rośnie. Jutro rozbieganie bardzo spokojnie, ok?', timestamp: d(-3) + 'T09:20:00', read: true },
  { id: 'm4', senderId: 'a1', content: 'Jasne! A kiedy możemy zaplanować kolejny wyścig próbny?', timestamp: d(-2) + 'T18:30:00', read: true },
  { id: 'm5', senderId: 'coach', content: 'Myślę o połowie marca. Ale najpierw zobaczmy jak pójdą następne 2 tygodnie.', timestamp: d(-2) + 'T19:00:00', read: false },
]

export const revenueHistory: Revenue[] = [
  { month: 'Wrzesień 2025', amount: 1248 },
  { month: 'Październik 2025', amount: 1847 },
  { month: 'Listopad 2025', amount: 1847 },
  { month: 'Grudzień 2025', amount: 2246 },
  { month: 'Styczeń 2026', amount: 2245 },
  { month: 'Luty 2026', amount: 2245 },
]

export const businessKpis = {
  mrr: 2245,
  activeAthletes: 6,
  feedbackRate: 87,
  avgLtv: 3152,
  newThisMonth: 1,
  overdueAmount: 1198,
  churnRate: 8.3,
}
